### ISSUE TITLE
Error get_config_latex

### ISSUE THREAD

**Issue by matheusullmann** [jacksonpradolima/roses#1]
` Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3079             try:
-> 3080                 return self._engine.get_loc(casted_key)
   3081             except KeyError as err:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'CCPSO2'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-10-bfad06eea0c8> in <module>
     22         return row['avg_std_effect']
     23 
---> 24 mean['latex_format'] = mean.apply(lambda row: get_config_latex(row, best, posthoc_df), axis=1)

~/.local/lib/python3.8/site-packages/pandas/core/frame.py in apply(self, func, axis, raw, result_type, args, **kwds)
   7763             kwds=kwds,
   7764         )
-> 7765         return op.get_result()
   7766 
   7767     def applymap(self, func, na_action: Optional[str] = None) -> DataFrame:

~/.local/lib/python3.8/site-packages/pandas/core/apply.py in get_result(self)
    183             return self.apply_raw()
    184 
--> 185         return self.apply_standard()
    186 
    187     def apply_empty_result(self):

~/.local/lib/python3.8/site-packages/pandas/core/apply.py in apply_standard(self)
    274 
    275     def apply_standard(self):
--> 276         results, res_index = self.apply_series_generator()
    277 
    278         # wrap results

~/.local/lib/python3.8/site-packages/pandas/core/apply.py in apply_series_generator(self)
    288             for i, v in enumerate(series_gen):
    289                 # ignore SettingWithCopy here in case the user mutates
--> 290                 results[i] = self.f(v)
    291                 if isinstance(results[i], ABCSeries):
    292                     # If we have a view on v, we need to make a copy because

<ipython-input-10-bfad06eea0c8> in <lambda>(row)
     22         return row['avg_std_effect']
     23 
---> 24 mean['latex_format'] = mean.apply(lambda row: get_config_latex(row, best, posthoc_df), axis=1)

<ipython-input-10-bfad06eea0c8> in get_config_latex(row, best, posthoc_df)
     13     elif current_name in posthoc_df.columns and best in posthoc_df.index and not np.isnan(posthoc_df.loc[best][current_name]):
     14         # They are equivalent
---> 15         is_equivalent = posthoc_df.loc[current_name][best] >= 0.05
     16 
     17     if is_equivalent:

~/.local/lib/python3.8/site-packages/pandas/core/indexing.py in __getitem__(self, key)
    893 
    894             maybe_callable = com.apply_if_callable(key, self.obj)
--> 895             return self._getitem_axis(maybe_callable, axis=axis)
    896 
    897     def _is_scalar_access(self, key: Tuple):

~/.local/lib/python3.8/site-packages/pandas/core/indexing.py in _getitem_axis(self, key, axis)
   1122         # fall thru to straight lookup
   1123         self._validate_key(key, axis)
-> 1124         return self._get_label(key, axis=axis)
   1125 
   1126     def _get_slice_axis(self, slice_obj: slice, axis: int):

~/.local/lib/python3.8/site-packages/pandas/core/indexing.py in _get_label(self, label, axis)
   1071     def _get_label(self, label, axis: int):
   1072         # GH#5667 this will fail if the label is not present in the axis.
-> 1073         return self.obj.xs(label, axis=axis)
   1074 
   1075     def _handle_lowerdim_multi_index_axis0(self, tup: Tuple):

~/.local/lib/python3.8/site-packages/pandas/core/generic.py in xs(self, key, axis, level, drop_level)
   3736                 raise TypeError(f"Expected label or tuple of labels, got {key}") from e
   3737         else:
-> 3738             loc = index.get_loc(key)
   3739 
   3740             if isinstance(loc, np.ndarray):

~/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3080                 return self._engine.get_loc(casted_key)
   3081             except KeyError as err:
-> 3082                 raise KeyError(key) from err
   3083 
   3084         if tolerance is not None:

KeyError: 'CCPSO2'`

**Comment by jacksonpradolima** [comment]
Hi @matheusullmann try to use this version:

`mean['eff_symbol'] = " "

            posthoc_df = None
            all_equivalent = False

            try:
                k = kruskal_wallis(x, column, 'name')
                kruskal, posthoc = k.apply(ax)
                print(f"\n{kruskal}")  # Kruskal results

                all_equivalent = 'p-unc' not in kruskal.columns or kruskal[
                    'p-unc'][0] >= 0.05

                if posthoc is not None:
                    print("\n--- POST-HOC TESTS ---")
                    print("\np-values:")
                    print(posthoc[0])

                    # Get the posthoc
                    df_eff = vargha_delaney.reduce(posthoc[1], best)

                    print(df_eff)

                    def get_eff_symbol(x, best, df_eff):
                        if x['name'] == best:
                            return "$\\bigstar$"
                        elif len(df_eff.loc[df_eff.compared_with == x['name'], 'effect_size_symbol'].values) > 0:
                            return df_eff.loc[df_eff.compared_with == x['name'], 'effect_size_symbol'].values[0]
                        else:
                            return df_eff.loc[df_eff.base == x['name'], 'effect_size_symbol'].values[0]

                    mean['eff_symbol'] = mean.apply(
                        lambda x: get_eff_symbol(x, best, df_eff), axis=1)

                    # Parse the posthoc to a dataframe in R because allows us
                    # to parse to pandas in Py
                    ro.r.assign('posthoc', posthoc[0])
                    ro.r('posthoc_table <- t(as.matrix(posthoc$p.value))')
                    ro.r('df_posthoc <- as.data.frame(t(posthoc_table))')

                    # Convert the dataframe from R to pandas
                    with localconverter(ro.default_converter + pandas2ri.converter):
                        posthoc_df = ro.conversion.rpy2py(ro.r('df_posthoc'))

            except Exception as e:
                print("\nError in statistical test:", exception_to_string(e))

            # Concat the values to a unique columns
            mean['avg_std_effect'] = mean.apply(
                lambda row: f"{row['mean']:.4f} $\\pm$ {row['std']:.4f} {row['eff_symbol']}".strip(), axis=1)

            def get_config_latex(row, best, posthoc_df, all_equivalent):
                """
                Latex commands used:
                - Best algorithm: \newcommand{\cellgray}[1]{\cellcolor{gray!30}{#1}}
                - Equivalent to the best one: \newcommand{\cellbold}[1]{\cellcolor{gray!30}{\textbf{#1}}}
                """
                current_name = row['name']

                if all_equivalent:
                    return f"\\cellgray{{{row['avg_std_effect']}}}"

                if row['name'] == best:
                    return f"\\cellbold{{{row['avg_std_effect']}}}"

                is_equivalent = False

                # If the posthoc was applied
                if posthoc_df is not None:
                    if best in posthoc_df.columns and current_name in posthoc_df.index and not np.isnan(
                            posthoc_df.loc[current_name][best]):
                        # They are equivalent
                        is_equivalent = posthoc_df.loc[
                            current_name][best] >= 0.05
                    elif current_name in posthoc_df.columns and best in posthoc_df.index and not np.isnan(
                            posthoc_df.loc[best][current_name]):
                        # They are equivalent
                        is_equivalent = posthoc_df.loc[
                            best][current_name] >= 0.05
                    else:
                        raise Exception(
                            "Problem found when we tried to find the post-hoc p-value")

                if is_equivalent:
                    return f"\\cellgray{{{row['avg_std_effect']}}}"

                return row['avg_std_effect']

            # Insert the latex commands
            mean['latex_format'] = mean.apply(lambda row: get_config_latex(
                row, best, posthoc_df, all_equivalent), axis=1)
`
